name = "fatappweb"
description = "FatApp web."
[project]
id = 87
name = "fatappweb"
runner = 0
repository = "fatappweb"
description = "fatappweb"
created_at = "2025-07-12T09:52:43.117655+00:00"
updated_at = "2025-07-12T09:52:43.117655+00:00"
