name = "fatappweb"
description = "FatApp web."

[project]
id = 3
name = "fatappweb"
runner = 0
deployment_method = 0
description = "fatappweb"
frontend_app_id = "6e84599a-5f5e-4c12-aee6-b766023a8901"
created_at = "2025-07-12T09:52:43.117655Z"
updated_at = "2025-07-12T09:52:43.117655Z"
